version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=user1
      - DB_PASSWORD=rootpassword
      - DB_NAME=strpass
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: strpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
